### ISSUE TITLE
hello friend I love this but I need video support

### ISSUE THREAD

**Issue by djblah** [j0nat/Windows-Live-Messenger#1]
hello friend I do not know if you would be so kind to be able to create a video and how to install it, a brief explanation on this
$encryption_key = 'CHANGE_ME_123456_123456_';
$encryption_iv = 'CHANGE_ME_123456';

also would like to know if the client's ip where it says localhost is to be replaced by global ip or rather the public ip for another person from another country to connect

add key="server_address" value="

**Comment by j0nat** [comment]
I made a quick video demonstration where I compile and set up the project using [WampServer](http://www.wampserver.com/en/) for database and webserver:
https://mega.nz/#!vugxQSQK!L_rcOq8VZGXhVCVO6W5v1kaA8urUWD8nHWhfa5wTF6g

The $encryption_key and $encryption_iv values are used for password encryption. See WLMServer\Database\PasswordEncrypter.cs and Registration Page\index.php. The values need to be changed in both Registration config.php and the server's Messenger.config. Keeping the same length but changing the characters. I **should** probably be hashing the passwords instead of encrypting them though!

The server_address value in the client's Messenger.config needs to point to your server. If your friend is not connected to your local network then he needs to set this value to be your public IP.

**Comment by djblah** [comment]
*********************cuestions????????????????******************************

After compiling open Messenger.config and insert the database information.
<appSettings>
  <add key="server_port" value="1323" />
  <add key="server_encryption_key" value="CHANGEME" />  ----->here the encryption can be sha1?
  <add key="database_host" value="localhost" />    ------>here the ip that asks for query the database is the default 127.0.0.1 or the public ?
  <add key="database_id" value="root" />
  <add key="database_password" value="" />
  <add key="database_password_encryption_key" value="CHANGE_ME_123456_123456_" /> ----->here the encryption can be sha1?
  <add key="database_password_encryption_iv" value="CHANGE_ME_123456" /> ----->here the encryption can be sha1?
  <add key="avatars_enabled" value="false" />
  <add key="avatars_address" value="" />  -----> this is the address of the folder where you keep the avatars?
  <add key="avatars_address_upload" value="" /> -----> this is the address of the upload.php file
  <add key="broadcast_interval" value="30" />
</appSettings>

Registration Page Installation
<?php
$dbhost = 'localhost';
$dbuser = 'root';
$dbpass = '';
$dbname = 'msn';
$encryption_key = 'CHANGE_ME_123456_123456_';  ----->here the encryption can be sha1?
$encryption_iv = 'CHANGE_ME_123456';  ----->here the encryption can be sha1?
?> 

After compiling open Messenger.config and insert the server address and port number.


<appSettings>
  <add key="server_address" value="127.0.0.1" />     --------> ip public??
  <add key="server_port" value="1323" />
</appSettings>


thank you for answering I would like to clarify that information because what I want is to put this project online

**Comment by djblah** [comment]
********** cuestion***************************
After compiling open Messenger.config and insert the database information.
`<appSettings>
  <add key="server_port" value="1323" />
  <add key="server_encryption_key" value="CHANGEME" />  ---> here change by sha1?
  <add key="database_host" value="localhost" />   ------> here goes the public ip or local ip 127.0.0.1
  <add key="database_id" value="root" />
  <add key="database_password" value="" />
  <add key="database_password_encryption_key" value="CHANGE_ME_123456_123456_" /> ---> here change by sha1?
  <add key="database_password_encryption_iv" value="CHANGE_ME_123456" />  ---> here change by sha1?
  <add key="avatars_enabled" value="false" />
  <add key="avatars_address" value="" />   ------> this is the address of the folder where avatars are stored  
  <add key="avatars_address_upload" value="" />  ----> this is the address where the file is located upload.php 
  <add key="broadcast_interval" value="30" />
</appSettings>`

Registration Page Installation

`<?php
$dbhost = 'localhost';     ------> here the public ip or the local ip 127.0.0.1
$dbuser = 'root';
$dbpass = '';
$dbname = 'msn';
$encryption_key = 'CHANGE_ME_123456_123456_';  ---> here change by sha1?
$encryption_iv = 'CHANGE_ME_123456';  ---> here change by sha1?
?> `


Client Installation


`<appSettings>
  <add key="server_address" value="127.0.0.1" />  ------>  here the public ip ?
  <add key="server_port" value="1323" />   ----->this is the port that this project uses?
</appSettings>`


thank you if you can clarify these these points that I wrote

**Comment by j0nat** [comment]
`<add key="server_encryption_key" value="CHANGEME" />---> here change by sha1?`
This is the encryption key used to encrypt the data sent between the server and the client. See [http://www.networkcomms.net/using-encryption/](http://www.networkcomms.net/using-encryption/). Change it to anything you like.
**IMPORTANT**: The change that you make to the server_encryption_key in the server config needs to also be changed in the WLMClient\Config.cs file on the WLM Client. The following line:
`        public static string SERVER_ENCRYPTION_KEY = "CHANGEME";`
After that you need to re-build the program in Visual Studio.


`<add key="database_host" value="localhost" /> ------> here goes the public ip or local ip 127.0.0.1`
127.0.0.1. This is the servers connection to your database.

`<add key="database_password_encryption_key" value="CHANGE_ME_123456_123456_" /> ---> here change by sha1?`
You can change this to anything you want to as long as you keep the length. For example:
20SKAW_WI_XKASJQ_9SJQUW_
8QKSXX_4D_IQUSHW_8CHRYW_
Q72BXO_TR_LX382Q_ISJ38F_

All of these random strings I've just made up are accepted values for database_password_encryption_key.

`<add key="database_password_encryption_iv" value="CHANGE_ME_123456" /> ---> here change by sha1?`
See database_password_encryption_key. Same thing.
9WUQJS_55_82UQHS
etc etc...


`<add key="avatars_address_upload" value="" /> ----> this is the address where the file is located upload.php`
This is the address where the users will upload their avatars. You need to use your public IP like this:
http://213.214.15.61/wlm/upload.php

`<add key="avatars_address" value="" /> ------> this is the address of the folder where avatars are stored`
This is where the users will retrieve their avatars from. It should look like this:
http://213.214.15.61/wlm/uploads/

`$dbhost = 'localhost'; ------> here the public ip or the local ip 127.0.0.1`
See database_host.

`$encryption_key = 'CHANGE_ME_123456_123456_'; ---> here change by sha1?`
See database_password_encryption_key. The database_password_encryption_key on the server and the $encryption_key value on the website needs to be identical. 

`$encryption_iv = 'CHANGE_ME_123456'; ---> here change by sha1?`
See database_password_encryption_iv. The database_password_encryption_iv on the server and the $encryption_iv value on the website needs to be identical.



`<add key="server_address" value="127.0.0.1" /> ------> here the public ip ?`
Yes. This is the address that the clients will use to connect to your server with. 

`<add key="server_port" value="1323" /> ----->this is the port that this project uses?`
Yes. This needs to be the same as the server_port setting on your server.

**Comment by djblah** [comment]
thanks for the explanation

**Comment by nahimov** [comment]
j0nat, could you please upload again video? The link https://mega.nz/#!vugxQSQK!L_rcOq8VZGXhVCVO6W5v1kaA8urUWD8nHWhfa5wTF6g has expired :-(
