### ISSUE TITLE
Avatar error 

### ISSUE THREAD

**Issue by w4rell** [j0nat/Windows-Live-Messenger#3]
Hi, I found your wonderful project thinking about how can it be possible no one had created a clone to messenger.
I'm stuck with avatars, created the folder uploads and set permissions (windows permissions) to total control on the folder and the upload.php file but wamp say :

`Undefined index on line 9 and 11`

I also tried to set the full path in the upload file but still the same error.

I really love your project, in parallel I'm recreating the original sign-up web page based on webarchive. And I'll also improve the design of the project to be more realistic.

![image](https://user-images.githubusercontent.com/11441252/50240590-77829d00-03c5-11e9-86a7-d0c854dddcb6.png)

If you can help me it would be awesome!

Thanks!

**Comment by w4rell** [comment]
I haven't found the avatar option on the application (but now yes), it works but if you want to improve the solution I can propose a new design and other little things :)

**Comment by j0nat** [comment]
Hi!

**Comment by j0nat** [comment]
> I haven't found the avatar option on the application (but now yes), it works but if you want to improve the solution I can propose a new design and other little things :)

Hi,

Please see issue https://github.com/j0nat/Windows-Live-Messenger/issues/1


(From the response) In the server config:
```
<add key="avatars_address_upload" value="" /> ----> this is the address where the file is located upload.php
This is the address where the users will upload their avatars. You need to use your public IP like this:
http://213.214.15.61/wlm/upload.php

<add key="avatars_address" value="" /> ------> this is the address of the folder where avatars are stored
This is where the users will retrieve their avatars from. It should look like this:
http://213.214.15.61/wlm/uploads/
> 
```

Your sign up page looks cool and I'm happy to take suggestions :).
