### ISSUE TITLE
WHAT I HAVE TO ADD ON THIS LINE (server_encryption_key)

### ISSUE THREAD

**Issue by djblah** [j0nat/Windows-Live-Messenger#4]
add key="server_encryption_key" value="CHANGEME"   -------<<

I do not understand that part that I have to add is a random name either or is a name of an encryption could help me with that

**Comment by j0nat** [comment]
**server_encryption_key**: What encryption key to use for communicating with the client. Needs to be the same as the compiled value in the WLMClient.

You can put anything you would like. Just make sure that what you put there is also in the client: https://github.com/j0nat/Windows-Live-Messenger/blob/master/WLMClient/Config/Properties.cs


`public static string SERVER_ENCRYPTION_KEY = "CHANGEME";`
