### ISSUE TITLE
Cannot found the package

### ISSUE THREAD

**Issue by dio85** [j0nat/Windows-Live-Messenger#5]
NetworkCommsDotNet on nugetpackage, but NetworkCommsDotNetComplete nothing. and now
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0246	The type or namespace name 'ProtobufSerializer' could not be found (are you missing a using directive or an assembly reference?)	WLMServer	C:\msn\Windows-Live-Messenger-master\WLMServer\Network\Server.cs	51		Active

**Comment by j0nat** [comment]
Normally you would find the NetworkCommsDotNetComplete download on their website which is the combined version that I've used in the project. Since their website is down I've uploaded it to releases:

https://github.com/j0nat/Windows-Live-Messenger/releases
